/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:fa1d0fdb-284d-4970-a6e6-6e751e0daf18",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_zhzAadq8P",
    "aws_user_pools_web_client_id": "53psi15o0qqs8m54r1mql88vv5",
    "oauth": {}
};


export default awsmobile;
